### ISSUE TITLE
A bit more explanation in "Deploy Node.js App Sections"

### ISSUE THREAD

**Issue by mhdawson** [nodeshift-blog-examples/kube-service-bindings-examples#2]
I think we should add a bit more info in the deploy sections, for example the command line to use with nodeshift to point to the right part of this repo.

This applies for all of the sub-examples

**Comment by pacostas** [comment]
Agree. So, the final result looks to me like moving half of [deploy nodejs application with nodeshift](https://github.com/nodeshift-blog-examples/kube-service-bindings-examples/blob/main/README.md#deploy-nodejs-application-with-nodeshift) section from common instructions to each sub-example, because the only difference for each sub-example is the directory and the namespace of the example.

**Comment by mhdawson** [comment]
@pacostas I think what you suggest makes sense.

**Comment by pacostas** [comment]
https://github.com/nodeshift-blog-examples/kube-service-bindings-examples/pull/7

**Comment by mhdawson** [comment]
Looks good, landed.
